### ISSUE TITLE
Not connecting to HomeKit

### ISSUE THREAD

**Issue by ziadi** [joggs/home_assistant_ebeco#1]
Hi,

The device can't be added to Homekit, the error message is:

Logger: homeassistant.components.homekit
Source: components/homekit/type_thermostats.py:427
Integration: HomeKit-brygga (documentation, issues)
First occurred: 2:11:20 (1 occurrences)
Last logged: 2:11:20

Failed to create a HomeKit accessory for climate.koket
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 522, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 237, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 221, in __init__
    self._async_update_state(state)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 427, in _async_update_state
    homekit_hvac_action = HC_HASS_TO_HOMEKIT_ACTION[hvac_action]
KeyError: 'heat'

**Comment by joggs** [comment]
Hi!
The error appars in the homekit integration and it looks like it has a problem with understanding the heat command. 
I am using standard variables from the homeassistant core, so I don't think the error is in my code.  I am not using homekit myself, so could you please post the configuration of your thermostat in homekit.

**Comment by ziadi** [comment]
> Hi!
> The error appars in the homekit integration and it looks like it has a problem with understanding the heat command.
> I am using standard variables from the homeassistant core, so I don't think the error is in my code. I am not using homekit myself, so could you please post the configuration of your thermostat in homekit.

Hello there,

Actually HA set up the configuration by it self in the UI and thought there is no need to add any configuration for Homekit.

**Comment by joggs** [comment]
Ok, I see.
Well, the error says KeyError: 'heat' which tells me that the string 'heat' is used in some way in the homekit integration. I am not using that string, I only use the recommended standard variable from Homeassistant called HVAC_MODE_HEAT  which always is correct as it comes from Home assistant core, so, I would say that either there is an error in the home kit addon or you have a mismatch in your addons/home assistant or there has been a breaking change in a new home assistant version that could cause this unfortunately. Please see if you can get an answer in the homekit forum regarding your problem and get back to me if you still think the problem is related to my addon
