### ISSUE TITLE
Fetch enery usage from the api.

### ISSUE THREAD

**Issue by pixiandreas** [joggs/home_assistant_ebeco#3]
Is it possible to add the enery usage to the integration ?
When i look at the API i see that you can "ask" for the energy usage:
 /api/services/app/Devices/GetUserDeviceEnergyData

More info here: https://ebecoconnect.com/swagger/index.html

**Comment by joggs** [comment]
Hi Andreas!
I was thinking of a good way to handle this when I created the integration, but the problem is that you can only get the energy usage for a specific date span in the past and not as a real time value. If you could get it in real time it would automatically be integrated in the history and you could se graphs of the energy usage but that is not possible unfortunately.  The api offers a way to get the total energy usage for a date span in the past as a list, which does not do very well as properties in this integration.  There are utility meter integrations in home assistant that maybe could be used if they can communicate with this api. That would probably give you the energy consuption date in a format that is of more use.
