### ISSUE TITLE
Removal of version in manifest.json broke addon

### ISSUE THREAD

**Issue by bergelfs** [joggs/home_assistant_ebeco#47]
This [commit](https://github.com/joggs/home_assistant_ebeco/commit/f28211851a4c788b440b919acac196ea2a6dc471) made the addon not load for me.
With this error message in the log:
> Setup failed for 'ebeco': Integration not found.

After adding back the version in maifest.json, it works again.
``` "version": "0.6.8" ```

**Comment by magnushegge** [comment]
Same here. After upgrading to  version 0.6.8 the update will not load with the following two items in log:

> Setup failed for 'ebeco': Integration not found.

> Failed to load integration for translation: Integration 'ebeco' not found.

Adding the version back to the manifest fixed the issue for me too.

**Comment by joggs** [comment]
Thanks for the info guys. I will fix it and blame ChatGPT.

*fixed in 0.6.10*

If you don't see the update, this manual refresh of HACS could help:

1. Open your Home Assistant interface and go to Settings.
2. Navigate to Devices & Services.
3. In the Integrations tab, locate HACS.
4. Click on the HACS integration card to open it.
5. Use the Reload or similar option to refresh HACS and its data.
